name: Build
description: |
  Builds the debian package represented by this repo at the ref pointed by the debain-ref argument.

on:
  workflow_dispatch:
    inputs:

      debian-ref:
        description: The debian ref to build. For example branch "qcom/debian/latest" or tag "debian/1.0.0-1"
        type: string
        required: true
        default: qcom/debian/latest

      force-docker-build:
        description: Force local pkg-builder instead of Debusine for Debian-family suites
        type: boolean
        default: false

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build
    uses: qualcomm-linux/qcom-build-utils/.github/workflows/pkg-build-reusable-workflow.yml@main
    with:
      qcom-build-utils-ref: main
      debian-ref: ${{ inputs.debian-ref }}
      force-docker-build: ${{ inputs.force-docker-build }}
      debusine-parent-workspace: ${{ vars.DEBUSINE_PARENT_WORKSPACE }}
    secrets:
      DEBUSINE_USER: ${{ secrets.DEBUSINE_USER }}
      DEBUSINE_TOKEN: ${{ secrets.DEBUSINE_TOKEN }}
