name: Release
description: |
  Release a new package version.
  This workflow is manually triggered via workflow_dispatch.
  Set repository variable IS_TEST_PKG=1 to run in test mode.

on:
  workflow_dispatch:
    inputs:
      debian-branch:
        description: The debian branch to release. For example branch "qcom/debian/trixie"
        type: string
        required: true

permissions:
  contents: write
  packages: read

jobs:
  Release:
    uses: qualcomm-linux/qcom-build-utils/.github/workflows/pkg-release-reusable-workflow.yml@main
    with:
      qcom-build-utils-ref: main
      debian-branch: ${{ github.event.inputs.debian-branch }}
      test-run: ${{ vars.IS_TEST_PKG == '1' || vars.IS_TEST_PKG == 'true' || vars['is-test-pkg'] == '1' || vars['is-test-pkg'] == 'true' }}
      debusine-parent-workspace: ${{ vars.DEBUSINE_PARENT_WORKSPACE }}
    secrets:
      PAT: ${{ secrets.DEB_PKG_BOT_CI_TOKEN }}
      DEBUSINE_USER: ${{ secrets.DEBUSINE_USER }}
      DEBUSINE_TOKEN: ${{ secrets.DEBUSINE_TOKEN }}
      DEBUSINE_RELEASE_TOKEN: ${{ secrets.DEBUSINE_RELEASE_TOKEN }}
      QSC_API_KEY: ${{ secrets.DEB_PKG_BOT_CI_QSC_TOKEN }}
