name: Release
description: |
  Release a new package version.
  This workflow is manually triggered via workflow_dispatch.

on:
  workflow_dispatch:
    inputs:

      debian-branch:
        description: The debian branch to release. For example branch "qcom/debian/trixie"
        type: string
        required: true

      test-run:
        description: |
          Debian: if true, stop after build/test.
          Ubuntu: still runs the full release flow.
        type: boolean
        default: true

permissions:
  contents: write
  packages: read

jobs:
  Release:
    uses: qualcomm-linux/qcom-build-utils/.github/workflows/pkg-release-reusable-workflow.yml@main
    with:
      qcom-build-utils-ref: main
      debian-branch: ${{ github.event.inputs.debian-branch }}
      test-run: ${{ github.event.inputs.test-run == 'true' && true || false }}
      debusine-parent-workspace: ${{ vars.DEBUSINE_PARENT_WORKSPACE }}
    secrets:
      PAT: ${{ secrets.DEB_PKG_BOT_CI_TOKEN }}
      DEBUSINE_USER: ${{ secrets.DEBUSINE_USER }}
      DEBUSINE_TOKEN: ${{ secrets.DEBUSINE_TOKEN }}
      DEBUSINE_RELEASE_TOKEN: ${{ secrets.DEBUSINE_RELEASE_TOKEN }}
      QSC_API_KEY: ${{ secrets.DEB_PKG_BOT_CI_QSC_TOKEN }}
